-- Status-derived columns from KiwiSDR /status endpoint
ALTER TABLE sources ADD COLUMN IF NOT EXISTS users INT DEFAULT 0;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS snr_dbm FLOAT;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS antenna TEXT;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS grid TEXT;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS ant_connected BOOLEAN;
ALTER TABLE sources ADD COLUMN IF NOT EXISTS offline BOOLEAN DEFAULT false;
