ALTER TABLE sources DROP COLUMN IF EXISTS users;
ALTER TABLE sources DROP COLUMN IF EXISTS snr_dbm;
ALTER TABLE sources DROP COLUMN IF EXISTS antenna;
ALTER TABLE sources DROP COLUMN IF EXISTS location;
ALTER TABLE sources DROP COLUMN IF EXISTS grid;
ALTER TABLE sources DROP COLUMN IF EXISTS status;
ALTER TABLE sources DROP COLUMN IF EXISTS ant_connected;
ALTER TABLE sources DROP COLUMN IF EXISTS offline;
